In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('dataset.csv')
dataset = dataset.iloc[:,1:]
dataset.head()

Spectral Centroid  Spectral Rolloff Point   Spectral Flux   Compactness  \
0               50.2                    0.316        0.000124        753.0   
1               45.4                    0.317        0.000066        714.0   
2               41.6                    0.283        0.000007        530.0   
3               50.7                    0.340        0.000084        766.0   
4               38.1                    0.268        0.000133        694.0   

   Spectral Variability   Root Mean Square   Fraction Of Low Energy Windows   \
0               0.000338            0.01280                     0.000000e+00   
1               0.000266            0.01030                     0.000000e+00   
2               0.000084            0.00337                     1.130000e-16   
3               0.000314            0.01240                     0.000000e+00   
4               0.000377            0.01490                     2.270000e-16   

   Zero Crossings   Strongest Frequency Via Zero Crossings   \
0             70.5                                   1100.0   
1             54.9                                    858.0   
2             62.6                                    978.0   
3             60.6                                    946.0   
4             56.4                                    882.0   

   Strongest Frequency Via Spectral Centroid    ...     \
0                                      1570.0   ...      
1                                      1420.0   ...      
2                                      1300.0   ...      
3                                      1590.0   ...      
4                                      1190.0   ...      

   Area Method of Moments of MFCCs 2  Area Method of Moments of MFCCs 3  \
0                              146.0                               3.15   
1                              141.0                              14.70   
2                              154.0                               4.60   
3                              142.0                              17.90   
4                              147.0                              11.60   

   Area Method of Moments of MFCCs 4  Area Method of Moments of MFCCs 5  \
0                         28600000.0                          1420000.0   
1                         27800000.0                          2520000.0   
2                         30500000.0                          1640000.0   
3                         28100000.0                          2860000.0   
4                         29400000.0                          2310000.0   

   Area Method of Moments of MFCCs 6  Area Method of Moments of MFCCs 7  \
0                            48600.0                       8.390000e+12   
1                           228000.0                       8.200000e+12   
2                            71500.0                       9.050000e+12   
3                           279000.0                       8.390000e+12   
4                           182000.0                       8.830000e+12   

   Area Method of Moments of MFCCs 8  Area Method of Moments of MFCCs 9  \
0                         13100000.0                           453000.0   
1                         23000000.0                          2090000.0   
2                         15000000.0                           656000.0   
3                         26100000.0                          2550000.0   
4                         20900000.0                          1660000.0   

   Area Method of Moments of MFCCs 10  Emotion  
0                        1.130000e+09    Angry  
1                        5.300000e+09    Angry  
2                        1.670000e+09    Angry  
3                        6.530000e+09    Angry  
4                        4.280000e+09    Angry  

[5 rows x 62 columns]

In [3]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 61].values

In [4]:
X

array([[5.02e+01, 3.16e-01, 1.24e-04, ..., 1.31e+07, 4.53e+05, 1.13e+09],
       [4.54e+01, 3.17e-01, 6.58e-05, ..., 2.30e+07, 2.09e+06, 5.30e+09],
       [4.16e+01, 2.83e-01, 6.59e-06, ..., 1.50e+07, 6.56e+05, 1.67e+09],
       ...,
       [5.38e+01, 3.16e-01, 1.41e-04, ..., 1.95e+08, 1.63e+07, 2.49e+11],
       [4.88e+01, 3.36e-01, 3.44e-04, ..., 1.72e+08, 1.40e+07, 2.14e+11],
       [5.70e+01, 3.35e-01, 2.63e-04, ..., 1.81e+08, 1.46e+07, 2.26e+11]])

In [5]:
y

array(['Angry', 'Angry', 'Angry', ..., 'Surprised', 'Surprised',
       'Surprised'], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(y)
y

array([0, 0, 0, ..., 7, 7, 7], dtype=int64)

In [7]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)
X

array([[ 0.78704605,  0.55582953, -0.21773949, ..., -1.29635735,
        -1.07181973, -0.90654751],
       [ 0.09843057,  0.58356995, -0.28200734, ..., -1.09849254,
        -0.72649185, -0.83994549],
       [-0.44672335, -0.35960454, -0.34739049, ..., -1.2583833 ,
        -1.02899654, -0.89792279],
       ...,
       [ 1.30350766,  0.55582953, -0.1989671 , ...,  2.33915878,
         2.27113136,  3.05235955],
       [ 0.58619987,  1.11063805,  0.02519739, ...,  1.87947284,
         1.78594252,  2.4933498 ],
       [ 1.76258464,  1.08289762, -0.06424756, ...,  2.05934995,
         1.91251352,  2.68501029]])

In [8]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [9]:
X_train

array([[-0.87710803, -0.6370088 ,  2.40597882, ..., -0.64280388,
        -0.22442688, -0.68182559],
       [-0.38933873, -0.02671942, -0.06866459, ..., -0.78270829,
        -0.95685107, -0.70738032],
       [ 0.91616145,  0.30616569, -0.34821869, ..., -0.59283801,
        -0.57460665, -0.64349349],
       ...,
       [ 0.28493059,  0.5280891 , -0.2254693 , ...,  1.04004636,
         0.89150745,  1.23158493],
       [ 0.68662296,  0.41712739, -0.29713568, ..., -0.38697866,
        -0.71383475, -0.57321798],
       [ 1.60477693,  0.97193592, -0.34501634, ..., -0.76472058,
        -0.95010062, -0.72974071]])

In [10]:
y_train

array([0, 6, 2, ..., 7, 4, 6], dtype=int64)

In [11]:
y_test.size

432

In [12]:
from sklearn import linear_model

In [13]:
mul_lr = linear_model.LogisticRegression(multi_class='multinomial', solver='newton-cg').fit(X_train, y_train)

In [14]:
y_pred = mul_lr.predict(X_test)
y_pred

array([0, 3, 2, 0, 3, 5, 7, 7, 6, 1, 3, 0, 6, 4, 0, 7, 3, 3, 1, 2, 6, 6,
       6, 2, 4, 3, 2, 2, 0, 1, 4, 6, 6, 3, 2, 4, 0, 1, 6, 0, 1, 6, 2, 1,
       4, 7, 0, 1, 7, 1, 6, 3, 7, 6, 3, 4, 2, 6, 5, 0, 2, 7, 7, 1, 7, 1,
       7, 0, 4, 6, 4, 1, 4, 0, 1, 1, 6, 1, 3, 3, 1, 0, 2, 6, 7, 6, 1, 0,
       0, 2, 2, 6, 4, 2, 2, 2, 2, 6, 6, 0, 3, 6, 3, 1, 4, 3, 7, 2, 6, 3,
       1, 4, 2, 2, 4, 4, 6, 3, 4, 6, 1, 1, 3, 0, 5, 2, 6, 2, 0, 3, 4, 5,
       3, 3, 1, 2, 6, 1, 7, 7, 4, 3, 3, 1, 0, 3, 1, 3, 4, 4, 0, 4, 6, 3,
       4, 2, 4, 1, 2, 1, 5, 1, 3, 2, 6, 0, 3, 0, 1, 3, 3, 4, 5, 3, 3, 7,
       0, 0, 7, 4, 4, 1, 4, 2, 4, 3, 6, 1, 2, 6, 2, 0, 2, 5, 2, 2, 7, 6,
       6, 7, 2, 6, 4, 7, 6, 7, 3, 7, 3, 5, 2, 4, 7, 7, 5, 1, 2, 6, 1, 0,
       4, 4, 1, 4, 0, 0, 2, 4, 7, 7, 6, 1, 5, 1, 4, 2, 7, 2, 7, 3, 3, 3,
       1, 6, 6, 1, 7, 0, 6, 0, 7, 1, 5, 1, 6, 0, 6, 3, 4, 1, 6, 2, 6, 4,
       6, 2, 7, 4, 7, 1, 1, 1, 5, 6, 3, 2, 4, 1, 6, 3, 7, 4, 0, 7, 1, 7,
       2, 7, 6, 3, 1, 0, 4, 7, 0, 2, 1, 7, 4, 4, 2,

In [15]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred)*100

In [16]:
accuracy

86.80555555555556

In [17]:
from sklearn.metrics import precision_recall_fscore_support

In [19]:
precision_recall_fscore_support(y_test,y_pred, average='weighted')

(0.8732587121899387, 0.8680555555555556, 0.8666573796598037, None)

In [20]:
dataset.corr()

Spectral Centroid  \
Spectral Centroid                                    1.000000   
Spectral Rolloff Point                               0.857682   
Spectral Flux                                       -0.108657   
Compactness                                          0.442807   
Spectral Variability                                -0.165645   
Root Mean Square                                    -0.162080   
Fraction Of Low Energy Windows                       0.026066   
Zero Crossings                                       0.695373   
Strongest Frequency Via Zero Crossings               0.695465   
Strongest Frequency Via Spectral Centroid            0.999909   
Strongest Frequency Via FFT Maximum                  0.816128   
MFCC 1                                               0.412217   
MFCC 2                                               0.119603   
MFCC 3                                              -0.028532   
MFCC 4                                              -0.059727   
MFCC 5                                               0.063733   
MFCC 6                                              -0.161312   
MFCC 7                                              -0.029376   
MFCC 8                                              -0.028659   
MFCC 9                                               0.075903   
MFCC 10                                              0.058673   
MFCC 11                                              0.108395   
MFCC 12                                              0.149721   
MFCC 13                                              0.163960   
LPC 1                                                0.757250   
LPC 2                                               -0.213883   
LPC 3                                               -0.090760   
LPC 4                                               -0.011242   
LPC 5                                               -0.213624   
LPC 6                                               -0.113852   
...                                                       ...   
LPC 8                                               -0.173891   
LPC 9                                               -0.288000   
LPC 10                                                    NaN   
Method of Moments 1                                 -0.147768   
Method of Moments 2                                  0.812546   
Method of Moments 3                                  0.259287   
Method of Moments 4                                  0.101453   
Method of Moments 5                                  0.018689   
Peak Based Spectral Smoothness                       0.366762   
Relative Difference Function                         0.415426   
Area Method of Moments 1                            -0.144546   
Area Method of Moments 2                             0.212835   
Area Method of Moments 3                             0.213875   
Area Method of Moments 4                             0.158498   
Area Method of Moments 5                             0.159247   
Area Method of Moments 6                             0.159988   
Area Method of Moments 7                             0.128903   
Area Method of Moments 8                             0.159109   
Area Method of Moments 9                             0.159850   
Area Method of Moments 10                            0.130319   
Area Method of Moments of MFCCs 1                    0.360961   
Area Method of Moments of MFCCs 2                    0.141763   
Area Method of Moments of MFCCs 3                    0.136020   
Area Method of Moments of MFCCs 4                    0.015440   
Area Method of Moments of MFCCs 5                    0.119602   
Area Method of Moments of MFCCs 6                    0.131753   
Area Method of Moments of MFCCs 7                    0.003954   
Area Method of Moments of MFCCs 8                    0.123000   
Area Method of Moments of MFCCs 9                    0.133569   
Area Method of Moments of MFCCs 10                   0.115397   

             