In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('dataset.csv')
dataset = dataset.iloc[:,1:]
dataset.head()

Spectral Centroid  Spectral Rolloff Point   Spectral Flux   Compactness  \
0               50.2                    0.316        0.000124        753.0   
1               45.4                    0.317        0.000066        714.0   
2               41.6                    0.283        0.000007        530.0   
3               50.7                    0.340        0.000084        766.0   
4               38.1                    0.268        0.000133        694.0   

   Spectral Variability   Root Mean Square   Fraction Of Low Energy Windows   \
0               0.000338            0.01280                     0.000000e+00   
1               0.000266            0.01030                     0.000000e+00   
2               0.000084            0.00337                     1.130000e-16   
3               0.000314            0.01240                     0.000000e+00   
4               0.000377            0.01490                     2.270000e-16   

   Zero Crossings   Strongest Frequency Via Zero Crossings   \
0             70.5                                   1100.0   
1             54.9                                    858.0   
2             62.6                                    978.0   
3             60.6                                    946.0   
4             56.4                                    882.0   

   Strongest Frequency Via Spectral Centroid    ...     \
0                                      1570.0   ...      
1                                      1420.0   ...      
2                                      1300.0   ...      
3                                      1590.0   ...      
4                                      1190.0   ...      

   Area Method of Moments of MFCCs 2  Area Method of Moments of MFCCs 3  \
0                              146.0                               3.15   
1                              141.0                              14.70   
2                              154.0                               4.60   
3                              142.0                              17.90   
4                              147.0                              11.60   

   Area Method of Moments of MFCCs 4  Area Method of Moments of MFCCs 5  \
0                         28600000.0                          1420000.0   
1                         27800000.0                          2520000.0   
2                         30500000.0                          1640000.0   
3                         28100000.0                          2860000.0   
4                         29400000.0                          2310000.0   

   Area Method of Moments of MFCCs 6  Area Method of Moments of MFCCs 7  \
0                            48600.0                       8.390000e+12   
1                           228000.0                       8.200000e+12   
2                            71500.0                       9.050000e+12   
3                           279000.0                       8.390000e+12   
4                           182000.0                       8.830000e+12   

   Area Method of Moments of MFCCs 8  Area Method of Moments of MFCCs 9  \
0                         13100000.0                           453000.0   
1                         23000000.0                          2090000.0   
2                         15000000.0                           656000.0   
3                         26100000.0                          2550000.0   
4                         20900000.0                          1660000.0   

   Area Method of Moments of MFCCs 10  Emotion  
0                        1.130000e+09    Angry  
1                        5.300000e+09    Angry  
2                        1.670000e+09    Angry  
3                        6.530000e+09    Angry  
4                        4.280000e+09    Angry  

[5 rows x 62 columns]

In [3]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 61].values

In [4]:
X

array([[5.02e+01, 3.16e-01, 1.24e-04, ..., 1.31e+07, 4.53e+05, 1.13e+09],
       [4.54e+01, 3.17e-01, 6.58e-05, ..., 2.30e+07, 2.09e+06, 5.30e+09],
       [4.16e+01, 2.83e-01, 6.59e-06, ..., 1.50e+07, 6.56e+05, 1.67e+09],
       ...,
       [5.38e+01, 3.16e-01, 1.41e-04, ..., 1.95e+08, 1.63e+07, 2.49e+11],
       [4.88e+01, 3.36e-01, 3.44e-04, ..., 1.72e+08, 1.40e+07, 2.14e+11],
       [5.70e+01, 3.35e-01, 2.63e-04, ..., 1.81e+08, 1.46e+07, 2.26e+11]])

In [5]:
y

array(['Angry', 'Angry', 'Angry', ..., 'Surprised', 'Surprised',
       'Surprised'], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(y)

In [7]:
y

array([0, 0, 0, ..., 7, 7, 7], dtype=int64)

In [8]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)
X

array([[ 0.78704605,  0.55582953, -0.21773949, ..., -1.29635735,
        -1.07181973, -0.90654751],
       [ 0.09843057,  0.58356995, -0.28200734, ..., -1.09849254,
        -0.72649185, -0.83994549],
       [-0.44672335, -0.35960454, -0.34739049, ..., -1.2583833 ,
        -1.02899654, -0.89792279],
       ...,
       [ 1.30350766,  0.55582953, -0.1989671 , ...,  2.33915878,
         2.27113136,  3.05235955],
       [ 0.58619987,  1.11063805,  0.02519739, ...,  1.87947284,
         1.78594252,  2.4933498 ],
       [ 1.76258464,  1.08289762, -0.06424756, ...,  2.05934995,
         1.91251352,  2.68501029]])

In [9]:
from sklearn.decomposition import PCA
pca = PCA(n_components = None)
pca.fit_transform(X)
explained_variance = pca.explained_variance_ratio_

In [10]:
explained_variance

array([2.72541600e-01, 2.16087071e-01, 1.05346342e-01, 7.26782082e-02,
       4.24447906e-02, 3.70149068e-02, 2.93230869e-02, 2.58861959e-02,
       2.08149182e-02, 1.66750265e-02, 1.56020288e-02, 1.18063815e-02,
       1.13426712e-02, 1.03143835e-02, 9.57404607e-03, 8.80839910e-03,
       8.52028094e-03, 8.06838488e-03, 7.04466038e-03, 6.84341970e-03,
       6.05970631e-03, 5.62997482e-03, 5.36495072e-03, 5.04713763e-03,
       4.73730279e-03, 4.61819385e-03, 4.29672807e-03, 3.63204847e-03,
       3.20612136e-03, 2.92343020e-03, 2.87758784e-03, 2.44835367e-03,
       2.27775246e-03, 2.11723958e-03, 1.62044170e-03, 1.51353384e-03,
       1.13648498e-03, 8.03662458e-04, 6.64120006e-04, 6.34542311e-04,
       3.93328351e-04, 3.80131169e-04, 2.47705798e-04, 1.99829131e-04,
       1.70478168e-04, 1.47968825e-04, 3.51210954e-05, 3.25746985e-05,
       3.11158760e-05, 8.78104245e-06, 3.53886450e-06, 1.45901375e-06,
       7.41431918e-07, 6.55960589e-07, 2.16240576e-07, 8.22352472e-08,
      

In [11]:
X[0].size

61

In [12]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [13]:
model = LogisticRegression() 
rfe = RFE(model, 3)

In [14]:
fit = rfe.fit(X, y)
fit.support_

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False,  True, False, False, False])

In [15]:
dataset.columns[34]

'Method of Moments 1'

In [16]:
fit.ranking_

array([47, 21, 10, 33, 12, 18, 55, 37, 19, 20, 44, 29, 35, 36, 17, 50, 39,
       49, 38, 58, 34, 40, 45, 46, 41, 22, 32, 27, 56, 54, 53, 43, 52, 59,
        1, 24, 48, 25, 23, 57, 51,  8, 16, 26, 42, 31,  7,  6, 30, 14, 13,
       28, 11,  4,  1,  9,  3,  1, 15,  5,  2])

In [17]:
c = 0
sum = 0
for p in explained_variance:
    sum = sum + p
    c = c + 1
    if c==27:
        break
sum

0.9724907956071576

In [222]:
pca = PCA(n_components = 27)
X1 = pca.fit_transform(X)
X1

array([[-8.91499020e-01, -2.40065870e+00, -3.50307719e+00, ...,
        -9.61641372e-01, -1.37509793e-01, -1.97006299e-01],
       [ 3.10323378e-01, -1.62402782e+00, -1.68416868e+00, ...,
        -4.43885886e-01, -4.21741249e-01, -4.52886327e-01],
       [ 9.19893168e-01, -4.00506522e+00, -6.75145344e-01, ...,
        -6.31036827e-01,  2.07523346e-01,  1.09508137e+00],
       ...,
       [-1.62914808e+00,  9.77153027e+00,  5.34433139e-01, ...,
        -3.32461451e-01, -2.83266609e-01,  1.29199384e-01],
       [-4.09179264e+00,  9.01184415e+00,  2.94260890e+00, ...,
        -1.55013997e+00, -2.54901815e-01,  2.68046035e-01],
       [ 3.54568031e+00,  4.37671102e+00, -3.08273873e+00, ...,
        -3.38559616e-01, -3.79309409e-03,  3.76839297e-01]])

In [223]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size = 0.3, random_state = 42)

In [224]:
X_train

array([[ 6.41137559,  0.63656029, -1.09668904, ..., -0.13497845,
        -0.1684313 , -0.07134832],
       [-1.20757406, -4.2928727 ,  1.85612169, ...,  0.27948102,
         0.35054221,  0.25684998],
       [ 0.86994682, -3.15562034, -2.47986455, ...,  0.44644859,
         0.60681289,  0.44593735],
       ...,
       [-0.57596816,  0.23776472,  0.70732716, ..., -0.01988195,
        -0.23936467,  0.33164037],
       [-0.9236599 , -2.17041888, -1.87999445, ...,  0.21232243,
         0.04560447,  0.03863583],
       [-7.07773552,  0.76955015, -2.23660675, ..., -0.3690979 ,
        -0.28602462, -0.6081942 ]])

In [225]:
y_train

array([0, 6, 2, ..., 7, 4, 6], dtype=int64)

In [226]:
y_test.size

432

In [227]:
from sklearn import linear_model

In [228]:
mul_lr = linear_model.LogisticRegression(multi_class='multinomial', solver='newton-cg').fit(X_train, y_train)
y_pred = mul_lr.predict(X_test)
y_pred

array([0, 3, 2, 0, 3, 5, 7, 7, 6, 1, 3, 0, 6, 4, 0, 7, 3, 4, 1, 2, 6, 6,
       6, 2, 4, 3, 2, 2, 0, 2, 4, 6, 6, 3, 2, 4, 0, 1, 6, 0, 1, 6, 2, 1,
       4, 7, 0, 1, 7, 1, 6, 3, 7, 6, 3, 4, 2, 6, 5, 0, 2, 7, 7, 1, 7, 1,
       7, 0, 4, 6, 4, 1, 4, 0, 1, 1, 6, 1, 3, 3, 2, 0, 2, 6, 7, 6, 1, 0,
       0, 2, 1, 6, 4, 2, 2, 2, 2, 6, 5, 0, 3, 6, 3, 1, 4, 3, 7, 2, 6, 3,
       1, 4, 2, 2, 4, 4, 6, 3, 4, 5, 1, 1, 4, 0, 5, 2, 6, 2, 0, 3, 4, 5,
       3, 4, 1, 2, 6, 1, 7, 7, 3, 3, 3, 1, 0, 3, 1, 3, 4, 4, 0, 4, 6, 3,
       4, 2, 4, 1, 2, 1, 5, 1, 3, 2, 6, 0, 3, 0, 1, 3, 3, 4, 5, 3, 4, 7,
       0, 0, 7, 4, 4, 1, 4, 2, 4, 3, 6, 1, 2, 6, 2, 0, 3, 5, 2, 2, 7, 6,
       6, 7, 2, 6, 4, 7, 6, 7, 3, 7, 5, 5, 2, 4, 7, 7, 5, 2, 1, 6, 1, 0,
       4, 4, 1, 4, 0, 0, 2, 4, 7, 4, 6, 1, 5, 1, 4, 2, 7, 2, 7, 3, 3, 3,
       1, 6, 6, 1, 7, 0, 6, 0, 7, 1, 6, 1, 6, 0, 6, 3, 4, 1, 5, 2, 6, 4,
       6, 1, 7, 4, 7, 1, 2, 1, 5, 6, 3, 2, 4, 1, 6, 3, 7, 4, 0, 7, 1, 7,
       2, 7, 6, 3, 1, 0, 4, 7, 0, 2, 1, 7, 4, 4, 2,

In [229]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred)*100

In [230]:
accuracy

88.42592592592592