In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
dataset = pd.read_csv('dataset.csv')
dataset = dataset.iloc[:,1:]
dataset.head()

Spectral Centroid  Spectral Rolloff Point   Spectral Flux   Compactness  \
0               50.2                    0.316        0.000124        753.0   
1               45.4                    0.317        0.000066        714.0   
2               41.6                    0.283        0.000007        530.0   
3               50.7                    0.340        0.000084        766.0   
4               38.1                    0.268        0.000133        694.0   

   Spectral Variability   Root Mean Square   Fraction Of Low Energy Windows   \
0               0.000338            0.01280                     0.000000e+00   
1               0.000266            0.01030                     0.000000e+00   
2               0.000084            0.00337                     1.130000e-16   
3               0.000314            0.01240                     0.000000e+00   
4               0.000377            0.01490                     2.270000e-16   

   Zero Crossings   Strongest Frequency Via Zero Crossings   \
0             70.5                                   1100.0   
1             54.9                                    858.0   
2             62.6                                    978.0   
3             60.6                                    946.0   
4             56.4                                    882.0   

   Strongest Frequency Via Spectral Centroid    ...     \
0                                      1570.0   ...      
1                                      1420.0   ...      
2                                      1300.0   ...      
3                                      1590.0   ...      
4                                      1190.0   ...      

   Area Method of Moments of MFCCs 2  Area Method of Moments of MFCCs 3  \
0                              146.0                               3.15   
1                              141.0                              14.70   
2                              154.0                               4.60   
3                              142.0                              17.90   
4                              147.0                              11.60   

   Area Method of Moments of MFCCs 4  Area Method of Moments of MFCCs 5  \
0                         28600000.0                          1420000.0   
1                         27800000.0                          2520000.0   
2                         30500000.0                          1640000.0   
3                         28100000.0                          2860000.0   
4                         29400000.0                          2310000.0   

   Area Method of Moments of MFCCs 6  Area Method of Moments of MFCCs 7  \
0                            48600.0                       8.390000e+12   
1                           228000.0                       8.200000e+12   
2                            71500.0                       9.050000e+12   
3                           279000.0                       8.390000e+12   
4                           182000.0                       8.830000e+12   

   Area Method of Moments of MFCCs 8  Area Method of Moments of MFCCs 9  \
0                         13100000.0                           453000.0   
1                         23000000.0                          2090000.0   
2                         15000000.0                           656000.0   
3                         26100000.0                          2550000.0   
4                         20900000.0                          1660000.0   

   Area Method of Moments of MFCCs 10  Emotion  
0                        1.130000e+09    Angry  
1                        5.300000e+09    Angry  
2                        1.670000e+09    Angry  
3                        6.530000e+09    Angry  
4                        4.280000e+09    Angry  

[5 rows x 62 columns]

In [13]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 61].values

In [22]:
X

array([[5.02e+01, 3.16e-01, 1.24e-04, ..., 1.31e+07, 4.53e+05, 1.13e+09],
       [4.54e+01, 3.17e-01, 6.58e-05, ..., 2.30e+07, 2.09e+06, 5.30e+09],
       [4.16e+01, 2.83e-01, 6.59e-06, ..., 1.50e+07, 6.56e+05, 1.67e+09],
       ...,
       [5.38e+01, 3.16e-01, 1.41e-04, ..., 1.95e+08, 1.63e+07, 2.49e+11],
       [4.88e+01, 3.36e-01, 3.44e-04, ..., 1.72e+08, 1.40e+07, 2.14e+11],
       [5.70e+01, 3.35e-01, 2.63e-04, ..., 1.81e+08, 1.46e+07, 2.26e+11]])

In [15]:
y

array(['Angry', 'Angry', 'Angry', ..., 'Surprised', 'Surprised',
       'Surprised'], dtype=object)

In [23]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(y)

In [31]:
y

array([0, 0, 0, ..., 7, 7, 7], dtype=int64)

In [32]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)
X

array([[ 0.78704605,  0.55582953, -0.21773949, ..., -1.29635735,
        -1.07181973, -0.90654751],
       [ 0.09843057,  0.58356995, -0.28200734, ..., -1.09849254,
        -0.72649185, -0.83994549],
       [-0.44672335, -0.35960454, -0.34739049, ..., -1.2583833 ,
        -1.02899654, -0.89792279],
       ...,
       [ 1.30350766,  0.55582953, -0.1989671 , ...,  2.33915878,
         2.27113136,  3.05235955],
       [ 0.58619987,  1.11063805,  0.02519739, ...,  1.87947284,
         1.78594252,  2.4933498 ],
       [ 1.76258464,  1.08289762, -0.06424756, ...,  2.05934995,
         1.91251352,  2.68501029]])

In [33]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [34]:
X_train

array([[-0.87710803, -0.6370088 ,  2.40597882, ..., -0.64280388,
        -0.22442688, -0.68182559],
       [-0.38933873, -0.02671942, -0.06866459, ..., -0.78270829,
        -0.95685107, -0.70738032],
       [ 0.91616145,  0.30616569, -0.34821869, ..., -0.59283801,
        -0.57460665, -0.64349349],
       ...,
       [ 0.28493059,  0.5280891 , -0.2254693 , ...,  1.04004636,
         0.89150745,  1.23158493],
       [ 0.68662296,  0.41712739, -0.29713568, ..., -0.38697866,
        -0.71383475, -0.57321798],
       [ 1.60477693,  0.97193592, -0.34501634, ..., -0.76472058,
        -0.95010062, -0.72974071]])

In [35]:
y_train

array([0, 6, 2, ..., 7, 4, 6], dtype=int64)

In [36]:
y_test.size

432